international/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from profiles import views as profiles_views
from contact import views as contact_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', profiles_views.ListPost.as_view(), name='home'),
    path('about/', profiles_views.about, name='about'),
    path('profile/', profiles_views.userProfile, name='profile'),
    path('<slug:slug>/', profiles_views.PostDetails.as_view(), name='post_detail'),
    path('contact/', contact_views.contact, name='contact'),
    path('account/', include('allauth.urls')),
    path('movue/', include('news.urls')),
    path('pay/', include('payroll.urls')),


]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from profiles import views as profiles_views
from contact import views as contact_views
from news import views as album_vies


urlpatterns = [
    path('album/', album_vies.AlbumView, name='album'),
    path('dashbord/', album_vies.AdminDashbord, name='dashbord'),
    path('newAlbum/', album_vies.ToaddAlbum.as_view(), name='newAlbum'),
    path('admin/dashbord/', album_vies.MyDaashoard, name='dashboard'),
    path('songNew/', album_vies.AddSongToAlbum.as_view(), name='song'),
    path('<int:id>', album_vies.AlbumDetails, name='album_details')
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payroll/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from payroll import views as pay_views


urlpatterns = [
    path('paying/', pay_views.payPall, name='paypall'),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models

# Create your models here.

news/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
STATUS =(
    (0, "Not Published"),
    (1, "Published")
)
class Album(models.Model):
    title       =       models.CharField(max_length=100)
    album_logo  =       models.ImageField(upload_to='logo')
    artist      =       models.CharField(max_length=200)
    status      =       models.IntegerField(choices=STATUS, default=0)


    def get_absolute_url(self):
        return reverse('album')
    def __str__(self):
        return self.title


class Song(models.Model):
    name            =       models.CharField(max_length=200)
    song_type       =       models.CharField(max_length=100)
    song_formt      =       models.CharField(max_length=20)
    album           =       models.ForeignKey(Album, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('album')
    def __str__(self):
        return self.name

payroll/models.py
from django.db import models

# Create your models here.

profiles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

STATUS = (
    (0, "Draft"),
    (1, "Publish")
)
class Post(models.Model):
    title      = models.CharField(max_length=200, unique=True)
    slug       = models.SlugField(max_length=200, unique=True)
    author     = models.ForeignKey(User, on_delete= models.CASCADE,related_name="blog_posts")
    updated_on = models.DateTimeField(auto_now=True)
    content    = models.TextField()
    created_on = models.DateTimeField(auto_now=True)
    status     = models.IntegerField(choices=STATUS, default=0)


    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

contact/forms.py
from django import forms

class ContactForm(forms.Form):
    name      = forms.CharField(required=False, max_length=100)
    email     = forms.EmailField(required=True)
    comments  = forms.CharField(required=True ,widget=forms.Textarea)

contact/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.conf import settings
from .forms import ContactForm

# Create your views here.
def contact(request):
    title = 'Contact'
    form = ContactForm(request.POST or None)
    confrm_message = None
    if form.is_valid():
        name = form.cleaned_data['name']
        comments = form.cleaned_data['comments']
        subject = 'Message from MYSITE.com'
        message = '%s %s' %(comments, name)
        email_from = form.cleaned_data['email']
        email_to = [settings.EMAIL_HOST_USER]
        send_mail(subject,message,email_from, email_to, fail_silently=False,)
        title = 'Thanks'
        confrm_message= 'Thanks for mailing me .'
        form = None
    context = {'title': title, 'form': form, 'confrm_message':confrm_message}

   
    template = 'contact.html'
    return render(request, template, context)

news/views.py
from django.views import generic
from django.views.generic.edit import CreateView
from django.shortcuts import render, get_object_or_404
from .models import Album, Song
# desplay the album with status 1 on my home page
def AlbumView(request):
    album = Album.objects.filter(status=1)
    context={
        'albums':album
    }
    template = 'album.html'
    return render(request, template, context)


#album detail views
def AlbumDetails(request, id):
    album_d = get_object_or_404(Album, pk=id)
    context = {
        'album_d':album_d
    }
    template = 'album_details.html'
    return render(request, template, context)

def AdminDashbord(request):
    template = 'index.html'
    return render(request,template)
def MyDaashoard(request):
    template = 'dashboard.html'
    return render(request,template)
#adding new album into my model
class ToaddAlbum(generic.CreateView):
    model = Album
    fields = ['title','artist','album_logo']
    template_name = 'album_form.html'
#adding song to album functin
class AddSongToAlbum(generic.CreateView):
    model = Song
    fields = ['name','song_type','song_formt','album']
    template_name = 'song_form.html'

payroll/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.
@login_required
def payPall(request):
	context= {}
	template = 'paypall.html'
	return render(request,template,context)

profiles/views.py
from django.views import generic
from .models import Post
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect


# Create your views here.
# def redirect_to(request):
#     response = redirect('/redirect-success/')
#
#     return response


def about(request):
    context= {}
    template = 'about.html'
    return render(request, template, context)

@login_required
def userProfile(request):
	user = request.user
	context= {'user': user}
	template = 'profile.html'
	return render(request,template,context)

#the functions to desplay postes on my page using generic vieews this desplaylist view

class ListPost(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'home.html'
#desplay details of our post
class PostDetails(generic.DetailView):
    model = Post
    template_name = 'post_detail.html'

contact/templates/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container ">
    <div class="row">
        <div class="col-sm-4 offset-4">

          <div>
            {% if confrm_message %}
              <p class="alert alert-danger">{{ confrm_message }}</p>
            {% endif %}
            {% if form %}
              <form method="POST" action=""> {% csrf_token %}

                {{ form |crispy }}
                  <input type="submit" value="submit" class=" btn btn-danger">
              </form>
              {% endif %}
            
          </div>
            </div>
    </div>
</div>
{% endblock %}

news/templates/album.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Albums</title>
</head>
<body>
{% block content %}
<div class="row">
    {% for album in albums %}
    <div class="col-md-4 offset-1">
        <div class="card">
            <div class="card-header">
                <h4>{{ album.title }}</h4>
            </div>
            <div class="card-body">
             <div class="row">
                    <div class="col-md-2">
                    <img src="{{ album.album_logo.url }}" height="100" width="100" class="rounded-circle img-responsive">
                </div>
                <div class="col-md-8 offset-2">
                    <h4>{{ album.artist |slice:":15"}}</h4>
                    <a href="{% url  'album_details' album.id %}  " class="btn btn-sm btn-danger">More >></a>
                </div>
             </div>
            </div>
        </div>
    </div>
        


    {% endfor %}
    </div>
{% endblock content %}
</body>
</html>

news/templates/album_details.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}

    {% for song in album_d.song_set.all %}

        <div class="card">
            <div class="card-header">
                    <h3>{{ song.name }}</h3>
            </div>
            <div class="card-bady">
                    <p>{{ song.song_type }}</p>
                     <p>{{ song.song_formt }}</p>
            </div>
        </div>

    {% endfor %}


{% endblock %}
</body>
</html>

news/templates/album_form.html
{% load crispy_forms_tags %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>


    <div class="row">
{% include 'header.html' %}
         <div class="col-md-8 offset-2">
                 <div class="card card-default">
                     <div class="card-header">

                     </div>
                <div class="card-body">
                    <form class="form-horizontal p-56" method="post" action=""enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div class="form-group">
                            <div class="col-md-offset-2">
                                <button type="submit" class="btn btn-danger">Submit</button>
                            </div>
                        </div>

                </form>
                </div>
            </div>
            </div>
        <div class="col-md-3 offset-3">

        </div>
        </div>
    </div>

</body>
</html>

news/templates/chart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="card ">
                <div class="card-header">
                    <h3>Line Series</h3>
                </div>
                <div class="card-block">
                    <div id="chart1"></div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card ">
                <div class="card-header">
                    <h3>Multiple Line Series</h3>
                </div>
                <div id="chart2" class="card-block">
                </div>
            </div>
        </div>
    </div>
</div>

<style>

</style>

<script type="text/javascript">
    jQuery(function ($) {
        var data1 = [12, 3, 4, 2, 12, 3, 4, 17, 22, 34, 54, 67];
        var data2 = [3, 9, 12, 14, 22, 32, 45, 12, 67, 45, 55, 7];
        var data3 = [23, 19, 11, 134, 242, 352, 435, 22, 637, 445, 555, 57];

        $(function () {
            $("#chart1").shieldChart({
                exportOptions: {
                    image: false,
                    print: false
                },
                axisY: {
                    title: {
                        text: "Break-Down for selected quarter"
                    }
                },
                dataSeries: [{
                    seriesType: "line",
                    data: data1
                }]
            });

            $("#chart2").shieldChart({
                exportOptions: {
                    image: false,
                    print: false
                },
                axisY: {
                    title: {
                        text: "Break-Down for selected quarter"
                    }
                },
                dataSeries: [{
                    seriesType: "line",
                    data: data2
                }, {
                    seriesType: "line",
                    data: data3
                }]
            });


        });

    });
</script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

news/templates/dashboard.html
{% include 'chart.html' %}

news/templates/header.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Dashboard </title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/dashboard/">

    <!-- Bootstrap core CSS -->
<link href="{% static 'bootstrap/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
  </head>
  <body>



<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">{{  user.username }}</a>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="#">Sign out</a>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'dashboard' %}">
              <span data-feather="home"></span>
              Dashboard <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'newAlbum' %}">
              <span data-feather="disc"></span>
              Album
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'song' %}">
              <span data-feather="music"></span>
              Song
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="users"></span>
              Customers
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="bar-chart-2"></span>
              Reports
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers"></span>
              Integrations
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="d-flex align-items-center text-muted" href="#">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Year-end sale
            </a>
          </li>
        </ul>
      </div>
    </nav>











    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="/docs/4.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
        <script src="{% static 'js/dashboard.js' %}"></script></body>
</html>

news/templates/index.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Dashboard</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/dashboard/">

    <!-- Bootstrap core CSS -->
<link href="{% static 'bootstrap/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
  </head>
  <body>
    {% include 'header.html' %}

{% block dashboard %}


    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="/docs/4.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
        <script src="{% static 'js/dashboard.js' %}"></script></body>
</html>

news/templates/song_form.html
{% load crispy_forms_tags %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>


    <div class="row">
{% include 'header.html' %}
         <div class="col-md-8 offset-2">
                 <div class="card card-default">
                     <div class="card-header">

                     </div>
                <div class="card-body">
                    <form class="form-horizontal p-56" method="post" action=""enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div class="form-group">
                            <div class="col-md-offset-2">
                                <button type="submit" class="btn btn-danger">Submit</button>
                            </div>
                        </div>

                </form>
                </div>
            </div>
            </div>
        <div class="col-md-3 offset-3">

        </div>
        </div>
    </div>

</body>
</html>

payroll/templates/paypall.html
{% extends 'base.html' %}

  {% block script %}
    <script src="https://js.stripe.com/v2/"></script>
<script src="https://js.stripe.com/v3/"></script>
  {% endblock %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>



{% block content %}

<!--<script src="https://js.stripe.com/v3/"></script>-->
<div class="container">
    <div class="row">
        <div class="col-md-7 offset-2">
            <div class="card mt-20 ">
                <div class="card-header bg-dark">
                    <h5>Payment</h5>
                </div>
                <div class="card-body">

                    <form action="/charge" method="post" id="payment-form" class="form">{% csrf_token %}
                  <div class="card-errors"></div>

                  <div class="form-row">
                    <label>
                      <span>Card number</span>
                      <input type="text" size="20" data-stripe="number" class="form-control">
                    </label>
                  </div>

                  <div class="form-row">
                    <label>
                      <span>Expiration (MM/YY)</span>
                      <input type="text" size="2" data-stripe="exp_month" >
                    </label>
                    <span> / </span>
                    <input type="text" size="2" data-stripe="exp_year" >
                  </div>

                  <div class="form-row">
                    <label>
                      <span>CVC</span>
                      <input type="text" size="4" data-stripe="cvc" class="form-control">
                    </label>
                  </div>

                  <div class="form-row">
                    <label>
                      <span>Billing Zip</span>
                      <input type="text" size="6" data-stripe="address_zip" class="form-control">
                    </label>
                  </div>

                 <input type="submit" class="submit btn-danger" value="Submit Payment" >
</form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
</body>
</html>

profiles/templates/about.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
{% block content %}
<h1>You ARE ON ABOUT PAGE</h1>
{% endblock %}
</body>
</html>

profiles/templates/home.html
{% extends 'base.html' %}

{% block jumbotron %}
  <div class="jumbotron">
    <div class="container">
      <h1 class="display-3">My Value My Proffesional</h1>
      <p>Find All Yoour Fava.</p>
      <p><a class="btn btn-danger btn-lg" href="#" role="button">Learn more &raquo;</a></p>
    </div>
  </div>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content|slice:":150" }}</p>
                    <a href="{% url 'post_detail' post.slug  %}" class="btn btn-danger btn-sm">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>

            {% block sidebar %}{% include 'sidebar.html' %} {% endblock sidebar%}

    </div>
</div>

{% endblock %}

profiles/templates/post_detail.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ object.content | safe }}</p>
      </div>
    </div>
    {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
  </div>
</div>

{% endblock content %}

profiles/templates/profile.html
{% extends 'base.html' %}


{% block content %}

{{ user.name }}
{{ user.email }}

{% endblock %}